version: '3.8'

services:
  db:
    build:
      context: ./database
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=farmacruz_db
      - POSTGRES_USER=farmacruz_user
      - POSTGRES_PASSWORD=supersecretpassword
    networks:
      - backend-net
    expose:
      - "5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn farmacruz_api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=farmacruz_db
      - POSTGRES_USER=farmacruz_user
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_HOST=db
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - db

  frontend:
    build:
      context: ./react
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "3000:5173"   # Vite dev server corre en 5173, mapeamos a 3000
    networks:
      - frontend-net
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  frontend-net:
    driver: bridge
  backend-net:
    driver: bridge
