###
curl -X POST http://localhost:8000/api/v1/auth/login \
  -H "Content-Type: application/x-www-form-urlencoded" \
  -d "username=admin&password=admin123"

### Categories
curl -X GET http://localhost:8000/api/v1/categories \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA"
###
curl -X POST http://localhost:8000/api/v1/categories \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA" \
  -H "Content-Type: application/json" \
  -d '{"name": "Vitaminas"}'

###
curl -X PUT http://localhost:8000/api/v1/categories/1 \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA" \
  -H "Content-Type: application/json" \
  -d '{"name": "Anabolicos"}'
###
curl -X DELETE http://localhost:8000/api/v1/categories/1 \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA"

### Products
curl -X GET http://localhost:8000/api/v1/products
###
curl -X GET http://localhost:8000/api/v1/products/1
###
curl -X POST http://localhost:8000/api/v1/products \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA" \
  -H "Content-Type: application/json" \
  -d '{
    "sku": "32342342",
    "name": "Vitamina C 1000mg",
    "description": "Refuerza el sistema inmunológico",
    "price": 199.99,
    "stock_count": 50,
    "category_id": 1
  }'
###
curl -X PUT http://localhost:8000/api/v1/products/1 \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "Vitamina C 1000mg (Actualizada)",
    "price": 179.99,
    "stock": 40
  }'
###
curl -X DELETE http://localhost:8000/api/v1/products/1 \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA"


### Carrito
curl -X GET http://localhost:8000/api/v1/orders/cart \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA"
###
curl -X POST http://localhost:8000/api/v1/orders/cart \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA" \
  -H "Content-Type: application/json" \
  -d '{
    "product_id": 1,
    "quantity": 2
  }'
###
curl -X DELETE http://localhost:8000/api/v1/orders/cart/1 \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA"

### Admin Dashboard 
curl -X GET http://localhost:8000/api/v1/admin/dashboard \
  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTc2MjQ0MjE4Mn0.6eUICpV3HxwtSDPZKj5ObWxAxYVzLOJ6gfgky-MuAaA"
